# coding: utf-8

"""
    Core API

    Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.front.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from front_core_python_sdk import schemas  # noqa: F401


class UpdateChannel(
    schemas.AnyTypeSchema,
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            name = schemas.StrSchema
            inbox_id = schemas.StrSchema
            
            
            class settings(
                schemas.DictSchema
            ):
            
            
                class MetaOapg:
                    
                    class properties:
                        
                        
                        class undo_send_time(
                            schemas.EnumBase,
                            schemas.IntSchema
                        ):
                            
                            @schemas.classproperty
                            def POSITIVE_0(cls):
                                return cls(0)
                            
                            @schemas.classproperty
                            def POSITIVE_5(cls):
                                return cls(5)
                            
                            @schemas.classproperty
                            def POSITIVE_10(cls):
                                return cls(10)
                            
                            @schemas.classproperty
                            def POSITIVE_15(cls):
                                return cls(15)
                            
                            @schemas.classproperty
                            def POSITIVE_30(cls):
                                return cls(30)
                            
                            @schemas.classproperty
                            def POSITIVE_60(cls):
                                return cls(60)
                        all_teammates_can_reply = schemas.BoolSchema
                        webhook_url = schemas.StrSchema
                        __annotations__ = {
                            "undo_send_time": undo_send_time,
                            "all_teammates_can_reply": all_teammates_can_reply,
                            "webhook_url": webhook_url,
                        }
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["undo_send_time"]) -> MetaOapg.properties.undo_send_time: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["all_teammates_can_reply"]) -> MetaOapg.properties.all_teammates_can_reply: ...
                
                @typing.overload
                def __getitem__(self, name: typing_extensions.Literal["webhook_url"]) -> MetaOapg.properties.webhook_url: ...
                
                @typing.overload
                def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
                
                def __getitem__(self, name: typing.Union[typing_extensions.Literal["undo_send_time", "all_teammates_can_reply", "webhook_url", ], str]):
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["undo_send_time"]) -> typing.Union[MetaOapg.properties.undo_send_time, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["all_teammates_can_reply"]) -> typing.Union[MetaOapg.properties.all_teammates_can_reply, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: typing_extensions.Literal["webhook_url"]) -> typing.Union[MetaOapg.properties.webhook_url, schemas.Unset]: ...
                
                @typing.overload
                def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
                
                def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["undo_send_time", "all_teammates_can_reply", "webhook_url", ], str]):
                    return super().get_item_oapg(name)
                
            
                def __new__(
                    cls,
                    *args: typing.Union[dict, frozendict.frozendict, ],
                    undo_send_time: typing.Union[MetaOapg.properties.undo_send_time, decimal.Decimal, int, schemas.Unset] = schemas.unset,
                    all_teammates_can_reply: typing.Union[MetaOapg.properties.all_teammates_can_reply, bool, schemas.Unset] = schemas.unset,
                    webhook_url: typing.Union[MetaOapg.properties.webhook_url, str, schemas.Unset] = schemas.unset,
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
                ) -> 'settings':
                    return super().__new__(
                        cls,
                        *args,
                        undo_send_time=undo_send_time,
                        all_teammates_can_reply=all_teammates_can_reply,
                        webhook_url=webhook_url,
                        _configuration=_configuration,
                        **kwargs,
                    )
            __annotations__ = {
                "name": name,
                "inbox_id": inbox_id,
                "settings": settings,
            }

    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["inbox_id"]) -> MetaOapg.properties.inbox_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["settings"]) -> MetaOapg.properties.settings: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "inbox_id", "settings", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["inbox_id"]) -> typing.Union[MetaOapg.properties.inbox_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["settings"]) -> typing.Union[MetaOapg.properties.settings, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "inbox_id", "settings", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        inbox_id: typing.Union[MetaOapg.properties.inbox_id, str, schemas.Unset] = schemas.unset,
        settings: typing.Union[MetaOapg.properties.settings, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateChannel':
        return super().__new__(
            cls,
            *args,
            name=name,
            inbox_id=inbox_id,
            settings=settings,
            _configuration=_configuration,
            **kwargs,
        )
