# coding: utf-8

"""
    Core API

    Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.front.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from front_core_python_sdk import schemas  # noqa: F401


class UpdateSignature(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    A signature that can be used to sign messages.
    """


    class MetaOapg:
        
        class properties:
            name = schemas.StrSchema
            sender_info = schemas.StrSchema
            body = schemas.StrSchema
            is_visible_for_all_teammate_channels = schemas.BoolSchema
            is_default = schemas.BoolSchema
        
            @staticmethod
            def channel_ids() -> typing.Type['UpdateSignatureChannelIds']:
                return UpdateSignatureChannelIds
            __annotations__ = {
                "name": name,
                "sender_info": sender_info,
                "body": body,
                "is_visible_for_all_teammate_channels": is_visible_for_all_teammate_channels,
                "is_default": is_default,
                "channel_ids": channel_ids,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> MetaOapg.properties.name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["sender_info"]) -> MetaOapg.properties.sender_info: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["body"]) -> MetaOapg.properties.body: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_visible_for_all_teammate_channels"]) -> MetaOapg.properties.is_visible_for_all_teammate_channels: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["is_default"]) -> MetaOapg.properties.is_default: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["channel_ids"]) -> 'UpdateSignatureChannelIds': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "sender_info", "body", "is_visible_for_all_teammate_channels", "is_default", "channel_ids", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union[MetaOapg.properties.name, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["sender_info"]) -> typing.Union[MetaOapg.properties.sender_info, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["body"]) -> typing.Union[MetaOapg.properties.body, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_visible_for_all_teammate_channels"]) -> typing.Union[MetaOapg.properties.is_visible_for_all_teammate_channels, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["is_default"]) -> typing.Union[MetaOapg.properties.is_default, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["channel_ids"]) -> typing.Union['UpdateSignatureChannelIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "sender_info", "body", "is_visible_for_all_teammate_channels", "is_default", "channel_ids", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        name: typing.Union[MetaOapg.properties.name, str, schemas.Unset] = schemas.unset,
        sender_info: typing.Union[MetaOapg.properties.sender_info, str, schemas.Unset] = schemas.unset,
        body: typing.Union[MetaOapg.properties.body, str, schemas.Unset] = schemas.unset,
        is_visible_for_all_teammate_channels: typing.Union[MetaOapg.properties.is_visible_for_all_teammate_channels, bool, schemas.Unset] = schemas.unset,
        is_default: typing.Union[MetaOapg.properties.is_default, bool, schemas.Unset] = schemas.unset,
        channel_ids: typing.Union['UpdateSignatureChannelIds', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'UpdateSignature':
        return super().__new__(
            cls,
            *args,
            name=name,
            sender_info=sender_info,
            body=body,
            is_visible_for_all_teammate_channels=is_visible_for_all_teammate_channels,
            is_default=is_default,
            channel_ids=channel_ids,
            _configuration=_configuration,
            **kwargs,
        )

from front_core_python_sdk.model.update_signature_channel_ids import UpdateSignatureChannelIds
