# coding: utf-8

"""
    Core API

    Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.front.com
"""

from front_core_python_sdk.paths.accounts_account_id_contacts.post import AddContactsToAccountRaw
from front_core_python_sdk.paths.accounts.post import CreateNewAccountRaw
from front_core_python_sdk.paths.accounts_account_id.delete import DeleteAccountRaw
from front_core_python_sdk.paths.accounts_account_id.get import GetAccountRaw
from front_core_python_sdk.paths.accounts_account_id_contacts.get import ListAccountContactsRaw
from front_core_python_sdk.paths.accounts.get import ListCompanyAccountsRaw
from front_core_python_sdk.paths.accounts_account_id_contacts.delete import RemoveContactFromRaw
from front_core_python_sdk.paths.accounts_account_id.patch import UpdateAccountRaw


class AccountsApiRaw(
    AddContactsToAccountRaw,
    CreateNewAccountRaw,
    DeleteAccountRaw,
    GetAccountRaw,
    ListAccountContactsRaw,
    ListCompanyAccountsRaw,
    RemoveContactFromRaw,
    UpdateAccountRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
