# coding: utf-8

"""
    Core API

    Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.front.com
"""

from front_core_python_sdk.paths.contacts.post import CreateNewContactRaw
from front_core_python_sdk.paths.teams_team_id_contacts.post import CreateTeamContactRaw
from front_core_python_sdk.paths.teammates_teammate_id_contacts.post import CreateTeammateContactRaw
from front_core_python_sdk.paths.contacts_contact_id.delete import DeleteContactRaw
from front_core_python_sdk.paths.contacts_contact_id.get import GetOneContactRaw
from front_core_python_sdk.paths.contacts.get import ListCompanyContactsRaw
from front_core_python_sdk.paths.contacts_contact_id_conversations.get import ListConversationsReverseChronologicalOrderRaw
from front_core_python_sdk.paths.teams_team_id_contacts.get import ListTeamContactsRaw
from front_core_python_sdk.paths.teammates_teammate_id_contacts.get import ListTeammateContactsRaw
from front_core_python_sdk.paths.contacts_merge.post import MergeContactsRaw
from front_core_python_sdk.paths.contacts_contact_id.patch import UpdateContactRaw


class ContactsApiRaw(
    CreateNewContactRaw,
    CreateTeamContactRaw,
    CreateTeammateContactRaw,
    DeleteContactRaw,
    GetOneContactRaw,
    ListCompanyContactsRaw,
    ListConversationsReverseChronologicalOrderRaw,
    ListTeamContactsRaw,
    ListTeammateContactsRaw,
    MergeContactsRaw,
    UpdateContactRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
