# coding: utf-8

"""
    Core API

    Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.front.com
"""

from front_core_python_sdk.paths.contacts.post import CreateNewContact
from front_core_python_sdk.paths.teams_team_id_contacts.post import CreateTeamContact
from front_core_python_sdk.paths.teammates_teammate_id_contacts.post import CreateTeammateContact
from front_core_python_sdk.paths.contacts_contact_id.delete import DeleteContact
from front_core_python_sdk.paths.contacts_contact_id.get import GetOneContact
from front_core_python_sdk.paths.contacts.get import ListCompanyContacts
from front_core_python_sdk.paths.contacts_contact_id_conversations.get import ListConversationsReverseChronologicalOrder
from front_core_python_sdk.paths.teams_team_id_contacts.get import ListTeamContacts
from front_core_python_sdk.paths.teammates_teammate_id_contacts.get import ListTeammateContacts
from front_core_python_sdk.paths.contacts_merge.post import MergeContacts
from front_core_python_sdk.paths.contacts_contact_id.patch import UpdateContact
from front_core_python_sdk.apis.tags.contacts_api_raw import ContactsApiRaw


class ContactsApi(
    CreateNewContact,
    CreateTeamContact,
    CreateTeammateContact,
    DeleteContact,
    GetOneContact,
    ListCompanyContacts,
    ListConversationsReverseChronologicalOrder,
    ListTeamContacts,
    ListTeammateContacts,
    MergeContacts,
    UpdateContact,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ContactsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ContactsApiRaw(api_client)
