# coding: utf-8

"""
    Core API

    Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.front.com
"""

from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_articles.post import CreateArticleDefaultLocale
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_locales_locale_articles.post import CreateArticleLocale
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_categories.post import CreateCategoryDefaultLocale
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_locales_locale_categories.post import CreateCategoryInLocale
from front_core_python_sdk.paths.knowledge_bases.post import CreateNewKnowledgeBase
from front_core_python_sdk.paths.knowledge_base_articles_article_id.delete import DeleteArticle
from front_core_python_sdk.paths.knowledge_base_categories_category_id.delete import DeleteCategory
from front_core_python_sdk.paths.knowledge_base_articles_article_id_download_attachment_id.get import DownloadAttachmentArticle
from front_core_python_sdk.paths.knowledge_base_articles_article_id.get import GetArticleById
from front_core_python_sdk.paths.knowledge_base_articles_article_id_locales_locale_content.get import GetArticleContent
from front_core_python_sdk.paths.knowledge_base_categories_category_id.get import GetCategory
from front_core_python_sdk.paths.knowledge_base_categories_category_id_content.get import GetCategoryContentDefaultLocale
from front_core_python_sdk.paths.knowledge_base_categories_category_id_locales_locale_content.get import GetCategoryContentLocale
from front_core_python_sdk.paths.knowledge_base_articles_article_id_content.get import GetContentDefaultLocale
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_content.get import GetContentDefaultLocale0
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id.get import GetKnowledgeBase
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_locales_locale_content.get import GetKnowledgeBaseContentInLocale
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_articles.get import ListArticlesInBase
from front_core_python_sdk.paths.knowledge_base_categories_category_id_articles.get import ListArticlesInCategory
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_categories.get import ListCategoriesInBase
from front_core_python_sdk.paths.knowledge_bases.get import ListKnowledgeBases
from front_core_python_sdk.paths.knowledge_base_articles_article_id_content.patch import UpdateArticleContentDefaultLocale
from front_core_python_sdk.paths.knowledge_base_articles_article_id_locales_locale_content.patch import UpdateArticleContentLocale
from front_core_python_sdk.paths.knowledge_base_categories_category_id_locales_locale_content.patch import UpdateCategoryContentLocale
from front_core_python_sdk.paths.knowledge_base_categories_category_id_content.patch import UpdateCategoryDefaultLocale
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_content.patch import UpdateDefaultKnowledgeBase
from front_core_python_sdk.paths.knowledge_bases_knowledge_base_id_locales_locale_content.patch import UpdateKnowledgeBaseLocale
from front_core_python_sdk.apis.tags.knowledge_bases_api_raw import KnowledgeBasesApiRaw


class KnowledgeBasesApi(
    CreateArticleDefaultLocale,
    CreateArticleLocale,
    CreateCategoryDefaultLocale,
    CreateCategoryInLocale,
    CreateNewKnowledgeBase,
    DeleteArticle,
    DeleteCategory,
    DownloadAttachmentArticle,
    GetArticleById,
    GetArticleContent,
    GetCategory,
    GetCategoryContentDefaultLocale,
    GetCategoryContentLocale,
    GetContentDefaultLocale,
    GetContentDefaultLocale0,
    GetKnowledgeBase,
    GetKnowledgeBaseContentInLocale,
    ListArticlesInBase,
    ListArticlesInCategory,
    ListCategoriesInBase,
    ListKnowledgeBases,
    UpdateArticleContentDefaultLocale,
    UpdateArticleContentLocale,
    UpdateCategoryContentLocale,
    UpdateCategoryDefaultLocale,
    UpdateDefaultKnowledgeBase,
    UpdateKnowledgeBaseLocale,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: KnowledgeBasesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = KnowledgeBasesApiRaw(api_client)
