# coding: utf-8

"""
    Core API

    Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.front.com
"""

from front_core_python_sdk.paths.rules_rule_id.get import GetRuleRaw
from front_core_python_sdk.paths.company_rules.get import ListAllCompanyRulesRaw
from front_core_python_sdk.paths.rules.get import ListCompanyRulesRaw
from front_core_python_sdk.paths.teams_team_id_rules.get import ListTeamRulesRaw
from front_core_python_sdk.paths.teammates_teammate_id_rules.get import ListTeammateRulesRaw


class RulesApiRaw(
    GetRuleRaw,
    ListAllCompanyRulesRaw,
    ListCompanyRulesRaw,
    ListTeamRulesRaw,
    ListTeammateRulesRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
