# coding: utf-8

"""
    Core API

    Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.front.com
"""

from front_core_python_sdk.paths.teams_team_id_signatures.post import CreateTeamSignatureRaw
from front_core_python_sdk.paths.teammates_teammate_id_signatures.post import CreateTeammateSignatureRaw
from front_core_python_sdk.paths.signatures_signature_id.delete import DeleteSignatureRaw
from front_core_python_sdk.paths.signatures_signature_id.get import GetSignatureRaw
from front_core_python_sdk.paths.teams_team_id_signatures.get import ListTeamRaw
from front_core_python_sdk.paths.teammates_teammate_id_signatures.get import ListTeammateRaw
from front_core_python_sdk.paths.signatures_signature_id.patch import UpdateSignatureRaw


class SignaturesApiRaw(
    CreateTeamSignatureRaw,
    CreateTeammateSignatureRaw,
    DeleteSignatureRaw,
    GetSignatureRaw,
    ListTeamRaw,
    ListTeammateRaw,
    UpdateSignatureRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
