# coding: utf-8

"""
    Core API

    Front is a customer operations platform that enables support, sales, and account management teams to deliver exceptional service at scale. Front streamlines customer communication by combining the efficiency of a help desk and the familiarity of email, with automated workflows and real-time collaboration behind the scenes.  With Front, teams can centralize messages across channels, route them to the right person, and unlock visibility and insights across all of their customer operations. More than 8000 businesses use Front to drive operational efficiency that prevents churn, improves retention, and propels customer growth.

    The version of the OpenAPI document: 1.0.0
    Created by: https://community.front.com
"""

from front_core_python_sdk.paths.teammates_teammate_id_inboxes.get import GetInboxList
from front_core_python_sdk.paths.teammates_teammate_id.get import GetTeammateById
from front_core_python_sdk.paths.teammates_teammate_id_conversations.get import ListAssignedConversations
from front_core_python_sdk.paths.teammates.get import ListCompanyMembers
from front_core_python_sdk.paths.teammates_teammate_id.patch import UpdateTeammate
from front_core_python_sdk.apis.tags.teammates_api_raw import TeammatesApiRaw


class TeammatesApi(
    GetInboxList,
    GetTeammateById,
    ListAssignedConversations,
    ListCompanyMembers,
    UpdateTeammate,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TeammatesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TeammatesApiRaw(api_client)
